commitizen:
  changelog_file: CHANGELOG.md
  changelog_incremental: true
  changelog_start_rev: 0.1.0
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.5.0
  version_files:
  - VERSION
