name: Bump version with commitizen
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Init git repository (to have a .git directory in it)
        run: |
          cd $GITHUB_WORKSPACE
          git init
          git branch -m main
          git config user.name Roberto Gianassi
          git config user.email roberto.gianassi+github.actions@gmail.com
          git commit --allow-empty -n -m "Initial commit."
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GH_ACTIONS_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GH_ACTIONS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Remove CHANGELOG.md
        uses: JesseTG/rm@v1.0.3
        with:
          path: CHANGELOG.md
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: body.md
      - name: Release with CHANGELOG
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
